### ISSUE TITLE
Smooth scrolling vs accessibility

### ISSUE THREAD

**Issue by thekid** [thekid/dialog#60]
![image](https://github.com/user-attachments/assets/2c259483-b522-46e0-94f8-1835a8bd9f9c)

See https://youtu.be/IP_rtWEMR0o?si=zi1NxOm861libo4S

**Comment by thekid** [comment]
Already implemented:

```css
/* See https://css-tricks.com/introduction-reduced-motion-media-query/ */
@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
    scroll-behavior: auto !important;
  }
}
```
